// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional session ID (auto-generated if empty)
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Agent configuration
	Config        *AgentConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateAgentRequest) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LLM provider: bedrock, openai, anthropic, openrouter, vertex
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Model ID (e.g., gpt-4o, anthropic.claude-sonnet-4-20250514-v1:0)
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Sampling temperature (0.0 - 1.0)
	Temperature float64 `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Maximum conversation turns
	MaxTurns int32 `protobuf:"varint,4,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`
	// Path to MCP servers configuration file
	McpConfigPath string `protobuf:"bytes,5,opt,name=mcp_config_path,json=mcpConfigPath,proto3" json:"mcp_config_path,omitempty"`
	// Filter to specific MCP servers
	SelectedServers []string `protobuf:"bytes,6,rep,name=selected_servers,json=selectedServers,proto3" json:"selected_servers,omitempty"`
	// Filter to specific tools (format: "server:tool")
	SelectedTools []string `protobuf:"bytes,7,rep,name=selected_tools,json=selectedTools,proto3" json:"selected_tools,omitempty"`
	// Custom system prompt
	SystemPrompt string `protobuf:"bytes,8,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Enable automatic context summarization
	EnableContextSummarization bool `protobuf:"varint,9,opt,name=enable_context_summarization,json=enableContextSummarization,proto3" json:"enable_context_summarization,omitempty"`
	// Enable context offloading for large outputs
	EnableContextOffloading bool `protobuf:"varint,10,opt,name=enable_context_offloading,json=enableContextOffloading,proto3" json:"enable_context_offloading,omitempty"`
	// Enable streaming responses
	EnableStreaming bool `protobuf:"varint,11,opt,name=enable_streaming,json=enableStreaming,proto3" json:"enable_streaming,omitempty"`
	// Custom tools with handlers on client side
	CustomTools   []*CustomToolDefinition `protobuf:"bytes,12,rep,name=custom_tools,json=customTools,proto3" json:"custom_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AgentConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AgentConfig) GetMaxTurns() int32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

func (x *AgentConfig) GetMcpConfigPath() string {
	if x != nil {
		return x.McpConfigPath
	}
	return ""
}

func (x *AgentConfig) GetSelectedServers() []string {
	if x != nil {
		return x.SelectedServers
	}
	return nil
}

func (x *AgentConfig) GetSelectedTools() []string {
	if x != nil {
		return x.SelectedTools
	}
	return nil
}

func (x *AgentConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentConfig) GetEnableContextSummarization() bool {
	if x != nil {
		return x.EnableContextSummarization
	}
	return false
}

func (x *AgentConfig) GetEnableContextOffloading() bool {
	if x != nil {
		return x.EnableContextOffloading
	}
	return false
}

func (x *AgentConfig) GetEnableStreaming() bool {
	if x != nil {
		return x.EnableStreaming
	}
	return false
}

func (x *AgentConfig) GetCustomTools() []*CustomToolDefinition {
	if x != nil {
		return x.CustomTools
	}
	return nil
}

type CustomToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique tool name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description for the LLM
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema for tool parameters
	Parameters *structpb.Struct `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Timeout for tool execution in milliseconds
	TimeoutMs int32 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Tool category (e.g., "utility", "data")
	Category      string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomToolDefinition) Reset() {
	*x = CustomToolDefinition{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomToolDefinition) ProtoMessage() {}

func (x *CustomToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomToolDefinition.ProtoReflect.Descriptor instead.
func (*CustomToolDefinition) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CustomToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomToolDefinition) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CustomToolDefinition) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CustomToolDefinition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Capabilities  *Capabilities          `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateAgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAgentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateAgentResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available tools (format: "server:tool")
	Tools []string `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	// Connected MCP servers
	Servers       []string `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Capabilities) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Capabilities  *Capabilities          `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	TokenUsage    *TokenUsage            `protobuf:"bytes,6,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAgentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetAgentResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetAgentResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentSummary        `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentsResponse) GetAgents() []*AgentSummary {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSummary) Reset() {
	*x = AgentSummary{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSummary) ProtoMessage() {}

func (x *AgentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSummary.ProtoReflect.Descriptor instead.
func (*AgentSummary) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DestroyAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAgentRequest) Reset() {
	*x = DestroyAgentRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAgentRequest) ProtoMessage() {}

func (x *DestroyAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAgentRequest.ProtoReflect.Descriptor instead.
func (*DestroyAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DestroyAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Destroyed     bool                   `protobuf:"varint,2,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAgentResponse) Reset() {
	*x = DestroyAgentResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAgentResponse) ProtoMessage() {}

func (x *DestroyAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAgentResponse.ProtoReflect.Descriptor instead.
func (*DestroyAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DestroyAgentResponse) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

type GetTokenUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenUsageRequest) Reset() {
	*x = GetTokenUsageRequest{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenUsageRequest) ProtoMessage() {}

func (x *GetTokenUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenUsageRequest.ProtoReflect.Descriptor instead.
func (*GetTokenUsageRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GetTokenUsageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CacheTokens      int32                  `protobuf:"varint,4,opt,name=cache_tokens,json=cacheTokens,proto3" json:"cache_tokens,omitempty"`
	ReasoningTokens  int32                  `protobuf:"varint,5,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	LlmCallCount     int32                  `protobuf:"varint,6,opt,name=llm_call_count,json=llmCallCount,proto3" json:"llm_call_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TokenUsage) GetCacheTokens() int32 {
	if x != nil {
		return x.CacheTokens
	}
	return 0
}

func (x *TokenUsage) GetReasoningTokens() int32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *TokenUsage) GetLlmCallCount() int32 {
	if x != nil {
		return x.LlmCallCount
	}
	return 0
}

type Costs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputCost     float64                `protobuf:"fixed64,1,opt,name=input_cost,json=inputCost,proto3" json:"input_cost,omitempty"`
	OutputCost    float64                `protobuf:"fixed64,2,opt,name=output_cost,json=outputCost,proto3" json:"output_cost,omitempty"`
	ReasoningCost float64                `protobuf:"fixed64,3,opt,name=reasoning_cost,json=reasoningCost,proto3" json:"reasoning_cost,omitempty"`
	CacheCost     float64                `protobuf:"fixed64,4,opt,name=cache_cost,json=cacheCost,proto3" json:"cache_cost,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Costs) Reset() {
	*x = Costs{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Costs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Costs) ProtoMessage() {}

func (x *Costs) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Costs.ProtoReflect.Descriptor instead.
func (*Costs) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Costs) GetInputCost() float64 {
	if x != nil {
		return x.InputCost
	}
	return 0
}

func (x *Costs) GetOutputCost() float64 {
	if x != nil {
		return x.OutputCost
	}
	return 0
}

func (x *Costs) GetReasoningCost() float64 {
	if x != nil {
		return x.ReasoningCost
	}
	return 0
}

func (x *Costs) GetCacheCost() float64 {
	if x != nil {
		return x.CacheCost
	}
	return 0
}

func (x *Costs) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type TokenUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenUsage    *TokenUsage            `protobuf:"bytes,1,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	Costs         *Costs                 `protobuf:"bytes,2,opt,name=costs,proto3" json:"costs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsageResponse) Reset() {
	*x = TokenUsageResponse{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageResponse) ProtoMessage() {}

func (x *TokenUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageResponse.ProtoReflect.Descriptor instead.
func (*TokenUsageResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *TokenUsageResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *TokenUsageResponse) GetCosts() *Costs {
	if x != nil {
		return x.Costs
	}
	return nil
}

type ConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID for the conversation
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConversationRequest_Question
	//	*ConversationRequest_ToolResult
	//	*ConversationRequest_Cancel
	Payload       isConversationRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationRequest) Reset() {
	*x = ConversationRequest{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRequest) ProtoMessage() {}

func (x *ConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRequest.ProtoReflect.Descriptor instead.
func (*ConversationRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ConversationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConversationRequest) GetPayload() isConversationRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConversationRequest) GetQuestion() *QuestionMessage {
	if x != nil {
		if x, ok := x.Payload.(*ConversationRequest_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *ConversationRequest) GetToolResult() *ToolResultMessage {
	if x != nil {
		if x, ok := x.Payload.(*ConversationRequest_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ConversationRequest) GetCancel() *CancelMessage {
	if x != nil {
		if x, ok := x.Payload.(*ConversationRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isConversationRequest_Payload interface {
	isConversationRequest_Payload()
}

type ConversationRequest_Question struct {
	// Client asks a question (optionally with history)
	Question *QuestionMessage `protobuf:"bytes,2,opt,name=question,proto3,oneof"`
}

type ConversationRequest_ToolResult struct {
	// Client returns result of a tool call
	ToolResult *ToolResultMessage `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ConversationRequest_Cancel struct {
	// Client requests cancellation
	Cancel *CancelMessage `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*ConversationRequest_Question) isConversationRequest_Payload() {}

func (*ConversationRequest_ToolResult) isConversationRequest_Payload() {}

func (*ConversationRequest_Cancel) isConversationRequest_Payload() {}

type QuestionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The question/prompt text
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Optional conversation history for multi-turn
	History       []*Message `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionMessage) Reset() {
	*x = QuestionMessage{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionMessage) ProtoMessage() {}

func (x *QuestionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionMessage.ProtoReflect.Descriptor instead.
func (*QuestionMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *QuestionMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionMessage) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

type ToolResultMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Call ID from ToolCallEvent
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Whether tool execution succeeded
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Tool output (if success)
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Error details (if not success)
	Error *ToolError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Execution duration in milliseconds
	DurationMs    int64 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultMessage) Reset() {
	*x = ToolResultMessage{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultMessage) ProtoMessage() {}

func (x *ToolResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultMessage.ProtoReflect.Descriptor instead.
func (*ToolResultMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ToolResultMessage) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResultMessage) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolResultMessage) GetError() *ToolError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ToolResultMessage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ToolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolError) Reset() {
	*x = ToolError{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolError) ProtoMessage() {}

func (x *ToolError) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolError.ProtoReflect.Descriptor instead.
func (*ToolError) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ToolError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ToolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type CancelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMessage) Reset() {
	*x = CancelMessage{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMessage) ProtoMessage() {}

func (x *CancelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMessage.ProtoReflect.Descriptor instead.
func (*CancelMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *CancelMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConversationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConversationResponse_TextChunk
	//	*ConversationResponse_ToolCall
	//	*ConversationResponse_AgentEvent
	//	*ConversationResponse_FinalResponse
	//	*ConversationResponse_Error
	Payload       isConversationResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ConversationResponse) GetPayload() isConversationResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConversationResponse) GetTextChunk() *TextChunkEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConversationResponse_TextChunk); ok {
			return x.TextChunk
		}
	}
	return nil
}

func (x *ConversationResponse) GetToolCall() *ToolCallEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConversationResponse_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ConversationResponse) GetAgentEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConversationResponse_AgentEvent); ok {
			return x.AgentEvent
		}
	}
	return nil
}

func (x *ConversationResponse) GetFinalResponse() *FinalResponse {
	if x != nil {
		if x, ok := x.Payload.(*ConversationResponse_FinalResponse); ok {
			return x.FinalResponse
		}
	}
	return nil
}

func (x *ConversationResponse) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConversationResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConversationResponse_Payload interface {
	isConversationResponse_Payload()
}

type ConversationResponse_TextChunk struct {
	// Streaming text chunk from LLM
	TextChunk *TextChunkEvent `protobuf:"bytes,1,opt,name=text_chunk,json=textChunk,proto3,oneof"`
}

type ConversationResponse_ToolCall struct {
	// Server requests tool execution from client
	ToolCall *ToolCallEvent `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ConversationResponse_AgentEvent struct {
	// Agent event for observability
	AgentEvent *AgentEvent `protobuf:"bytes,3,opt,name=agent_event,json=agentEvent,proto3,oneof"`
}

type ConversationResponse_FinalResponse struct {
	// Final response (conversation complete)
	FinalResponse *FinalResponse `protobuf:"bytes,4,opt,name=final_response,json=finalResponse,proto3,oneof"`
}

type ConversationResponse_Error struct {
	// Error event
	Error *ErrorEvent `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ConversationResponse_TextChunk) isConversationResponse_Payload() {}

func (*ConversationResponse_ToolCall) isConversationResponse_Payload() {}

func (*ConversationResponse_AgentEvent) isConversationResponse_Payload() {}

func (*ConversationResponse_FinalResponse) isConversationResponse_Payload() {}

func (*ConversationResponse_Error) isConversationResponse_Payload() {}

type TextChunkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text content chunk
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Whether this is thinking/reasoning (for reasoning models)
	IsThinking    bool `protobuf:"varint,2,opt,name=is_thinking,json=isThinking,proto3" json:"is_thinking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunkEvent) Reset() {
	*x = TextChunkEvent{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunkEvent) ProtoMessage() {}

func (x *TextChunkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunkEvent.ProtoReflect.Descriptor instead.
func (*TextChunkEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *TextChunkEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextChunkEvent) GetIsThinking() bool {
	if x != nil {
		return x.IsThinking
	}
	return false
}

type ToolCallEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique call ID for matching result
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Tool name to execute
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as JSON object
	Arguments *structpb.Struct `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	// Timeout for this tool call in milliseconds
	TimeoutMs     int32 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEvent) Reset() {
	*x = ToolCallEvent{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEvent) ProtoMessage() {}

func (x *ToolCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEvent.ProtoReflect.Descriptor instead.
func (*ToolCallEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ToolCallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallEvent) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCallEvent) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type FinalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Final response text
	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// Updated conversation messages
	UpdatedMessages []*Message `protobuf:"bytes,2,rep,name=updated_messages,json=updatedMessages,proto3" json:"updated_messages,omitempty"`
	// Token usage for this conversation
	TokenUsage *TokenUsage `protobuf:"bytes,3,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	// Total duration in milliseconds
	DurationMs    int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalResponse) Reset() {
	*x = FinalResponse{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResponse) ProtoMessage() {}

func (x *FinalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResponse.ProtoReflect.Descriptor instead.
func (*FinalResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *FinalResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *FinalResponse) GetUpdatedMessages() []*Message {
	if x != nil {
		return x.UpdatedMessages
	}
	return nil
}

func (x *FinalResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *FinalResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ErrorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code (e.g., AGENT_NOT_FOUND, ASK_FAILED)
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Additional error details
	Details *structpb.Struct `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// If true, the stream is terminated
	Fatal         bool `protobuf:"varint,4,opt,name=fatal,proto3" json:"fatal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorEvent) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

type AgentEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type (e.g., "agent_start", "tool_call", "llm_request")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Event timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Trace ID for distributed tracing
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Span ID within the trace
	SpanId string `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Parent span ID
	ParentId string `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Correlation ID for related events
	CorrelationId string `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Hierarchy level in the call stack
	HierarchyLevel int32 `protobuf:"varint,7,opt,name=hierarchy_level,json=hierarchyLevel,proto3" json:"hierarchy_level,omitempty"`
	// Session ID
	SessionId string `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Component that emitted the event
	Component string `protobuf:"bytes,9,opt,name=component,proto3" json:"component,omitempty"`
	// Event-specific data as JSON object
	Data          *structpb.Struct `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *AgentEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AgentEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AgentEvent) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *AgentEvent) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *AgentEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentEvent) GetHierarchyLevel() int32 {
	if x != nil {
		return x.HierarchyLevel
	}
	return 0
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *AgentEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role: "user", "assistant", "system"
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Message content
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{27}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{28}
}

func (x *AskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	TokenUsage    *TokenUsage            `protobuf:"bytes,2,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{29}
}

func (x *AskResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AskResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *AskResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type AskWithHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskWithHistoryRequest) Reset() {
	*x = AskWithHistoryRequest{}
	mi := &file_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskWithHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskWithHistoryRequest) ProtoMessage() {}

func (x *AskWithHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskWithHistoryRequest.ProtoReflect.Descriptor instead.
func (*AskWithHistoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{30}
}

func (x *AskWithHistoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AskWithHistoryRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AskWithHistoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	UpdatedMessages []*Message             `protobuf:"bytes,2,rep,name=updated_messages,json=updatedMessages,proto3" json:"updated_messages,omitempty"`
	TokenUsage      *TokenUsage            `protobuf:"bytes,3,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	DurationMs      int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AskWithHistoryResponse) Reset() {
	*x = AskWithHistoryResponse{}
	mi := &file_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskWithHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskWithHistoryResponse) ProtoMessage() {}

func (x *AskWithHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskWithHistoryResponse.ProtoReflect.Descriptor instead.
func (*AskWithHistoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{31}
}

func (x *AskWithHistoryResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AskWithHistoryResponse) GetUpdatedMessages() []*Message {
	if x != nil {
		return x.UpdatedMessages
	}
	return nil
}

func (x *AskWithHistoryResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *AskWithHistoryResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{32}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{33}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\vmcpagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"e\n" +
	"\x12CreateAgentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x06config\x18\x02 \x01(\v2\x18.mcpagent.v1.AgentConfigR\x06config\"\x91\x04\n" +
	"\vAgentConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1b\n" +
	"\tmax_turns\x18\x04 \x01(\x05R\bmaxTurns\x12&\n" +
	"\x0fmcp_config_path\x18\x05 \x01(\tR\rmcpConfigPath\x12)\n" +
	"\x10selected_servers\x18\x06 \x03(\tR\x0fselectedServers\x12%\n" +
	"\x0eselected_tools\x18\a \x03(\tR\rselectedTools\x12#\n" +
	"\rsystem_prompt\x18\b \x01(\tR\fsystemPrompt\x12@\n" +
	"\x1cenable_context_summarization\x18\t \x01(\bR\x1aenableContextSummarization\x12:\n" +
	"\x19enable_context_offloading\x18\n" +
	" \x01(\bR\x17enableContextOffloading\x12)\n" +
	"\x10enable_streaming\x18\v \x01(\bR\x0fenableStreaming\x12D\n" +
	"\fcustom_tools\x18\f \x03(\v2!.mcpagent.v1.CustomToolDefinitionR\vcustomTools\"\xc0\x01\n" +
	"\x14CustomToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"\xe1\x01\n" +
	"\x13CreateAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x19.mcpagent.v1.CapabilitiesR\fcapabilities\">\n" +
	"\fCapabilities\x12\x14\n" +
	"\x05tools\x18\x01 \x03(\tR\x05tools\x12\x18\n" +
	"\aservers\x18\x02 \x03(\tR\aservers\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x98\x02\n" +
	"\x10GetAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x19.mcpagent.v1.CapabilitiesR\fcapabilities\x128\n" +
	"\vtoken_usage\x18\x06 \x01(\v2\x17.mcpagent.v1.TokenUsageR\n" +
	"tokenUsage\"\x13\n" +
	"\x11ListAgentsRequest\"G\n" +
	"\x12ListAgentsResponse\x121\n" +
	"\x06agents\x18\x01 \x03(\v2\x19.mcpagent.v1.AgentSummaryR\x06agents\"\x9b\x01\n" +
	"\fAgentSummary\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\x13DestroyAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"O\n" +
	"\x14DestroyAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\tdestroyed\x18\x02 \x01(\bR\tdestroyed\"1\n" +
	"\x14GetTokenUsageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xf5\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12!\n" +
	"\fcache_tokens\x18\x04 \x01(\x05R\vcacheTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x05 \x01(\x05R\x0freasoningTokens\x12$\n" +
	"\x0ellm_call_count\x18\x06 \x01(\x05R\fllmCallCount\"\xac\x01\n" +
	"\x05Costs\x12\x1d\n" +
	"\n" +
	"input_cost\x18\x01 \x01(\x01R\tinputCost\x12\x1f\n" +
	"\voutput_cost\x18\x02 \x01(\x01R\n" +
	"outputCost\x12%\n" +
	"\x0ereasoning_cost\x18\x03 \x01(\x01R\rreasoningCost\x12\x1d\n" +
	"\n" +
	"cache_cost\x18\x04 \x01(\x01R\tcacheCost\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x01R\ttotalCost\"x\n" +
	"\x12TokenUsageResponse\x128\n" +
	"\vtoken_usage\x18\x01 \x01(\v2\x17.mcpagent.v1.TokenUsageR\n" +
	"tokenUsage\x12(\n" +
	"\x05costs\x18\x02 \x01(\v2\x12.mcpagent.v1.CostsR\x05costs\"\xf0\x01\n" +
	"\x13ConversationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12:\n" +
	"\bquestion\x18\x02 \x01(\v2\x1c.mcpagent.v1.QuestionMessageH\x00R\bquestion\x12A\n" +
	"\vtool_result\x18\x03 \x01(\v2\x1e.mcpagent.v1.ToolResultMessageH\x00R\n" +
	"toolResult\x124\n" +
	"\x06cancel\x18\x04 \x01(\v2\x1a.mcpagent.v1.CancelMessageH\x00R\x06cancelB\t\n" +
	"\apayload\"U\n" +
	"\x0fQuestionMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12.\n" +
	"\ahistory\x18\x02 \x03(\v2\x14.mcpagent.v1.MessageR\ahistory\"\xad\x01\n" +
	"\x11ToolResultMessage\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x16.mcpagent.v1.ToolErrorR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"l\n" +
	"\tToolError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\"'\n" +
	"\rCancelMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xcc\x02\n" +
	"\x14ConversationResponse\x12<\n" +
	"\n" +
	"text_chunk\x18\x01 \x01(\v2\x1b.mcpagent.v1.TextChunkEventH\x00R\ttextChunk\x129\n" +
	"\ttool_call\x18\x02 \x01(\v2\x1a.mcpagent.v1.ToolCallEventH\x00R\btoolCall\x12:\n" +
	"\vagent_event\x18\x03 \x01(\v2\x17.mcpagent.v1.AgentEventH\x00R\n" +
	"agentEvent\x12C\n" +
	"\x0efinal_response\x18\x04 \x01(\v2\x1a.mcpagent.v1.FinalResponseH\x00R\rfinalResponse\x12/\n" +
	"\x05error\x18\x05 \x01(\v2\x17.mcpagent.v1.ErrorEventH\x00R\x05errorB\t\n" +
	"\apayload\"E\n" +
	"\x0eTextChunkEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vis_thinking\x18\x02 \x01(\bR\n" +
	"isThinking\"\x9b\x01\n" +
	"\rToolCallEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\xc7\x01\n" +
	"\rFinalResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12?\n" +
	"\x10updated_messages\x18\x02 \x03(\v2\x14.mcpagent.v1.MessageR\x0fupdatedMessages\x128\n" +
	"\vtoken_usage\x18\x03 \x01(\v2\x17.mcpagent.v1.TokenUsageR\n" +
	"tokenUsage\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\x83\x01\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x12\x14\n" +
	"\x05fatal\x18\x04 \x01(\bR\x05fatal\"\xe5\x02\n" +
	"\n" +
	"AgentEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12'\n" +
	"\x0fhierarchy_level\x18\a \x01(\x05R\x0ehierarchyLevel\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x1c\n" +
	"\tcomponent\x18\t \x01(\tR\tcomponent\x12+\n" +
	"\x04data\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x04data\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"C\n" +
	"\n" +
	"AskRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"\x84\x01\n" +
	"\vAskResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x128\n" +
	"\vtoken_usage\x18\x02 \x01(\v2\x17.mcpagent.v1.TokenUsageR\n" +
	"tokenUsage\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"d\n" +
	"\x15AskWithHistoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.mcpagent.v1.MessageR\bmessages\"\xd0\x01\n" +
	"\x16AskWithHistoryResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12?\n" +
	"\x10updated_messages\x18\x02 \x03(\v2\x14.mcpagent.v1.MessageR\x0fupdatedMessages\x128\n" +
	"\vtoken_usage\x18\x03 \x01(\v2\x17.mcpagent.v1.TokenUsageR\n" +
	"tokenUsage\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xde\x05\n" +
	"\fAgentService\x12P\n" +
	"\vCreateAgent\x12\x1f.mcpagent.v1.CreateAgentRequest\x1a .mcpagent.v1.CreateAgentResponse\x12G\n" +
	"\bGetAgent\x12\x1c.mcpagent.v1.GetAgentRequest\x1a\x1d.mcpagent.v1.GetAgentResponse\x12M\n" +
	"\n" +
	"ListAgents\x12\x1e.mcpagent.v1.ListAgentsRequest\x1a\x1f.mcpagent.v1.ListAgentsResponse\x12S\n" +
	"\fDestroyAgent\x12 .mcpagent.v1.DestroyAgentRequest\x1a!.mcpagent.v1.DestroyAgentResponse\x12S\n" +
	"\rGetTokenUsage\x12!.mcpagent.v1.GetTokenUsageRequest\x1a\x1f.mcpagent.v1.TokenUsageResponse\x12S\n" +
	"\bConverse\x12 .mcpagent.v1.ConversationRequest\x1a!.mcpagent.v1.ConversationResponse(\x010\x01\x128\n" +
	"\x03Ask\x12\x17.mcpagent.v1.AskRequest\x1a\x18.mcpagent.v1.AskResponse\x12Y\n" +
	"\x0eAskWithHistory\x12\".mcpagent.v1.AskWithHistoryRequest\x1a#.mcpagent.v1.AskWithHistoryResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.mcpagent.v1.HealthCheckRequest\x1a .mcpagent.v1.HealthCheckResponseB,Z*github.com/mcpagent/mcpagent/grpcserver/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_agent_proto_goTypes = []any{
	(*CreateAgentRequest)(nil),     // 0: mcpagent.v1.CreateAgentRequest
	(*AgentConfig)(nil),            // 1: mcpagent.v1.AgentConfig
	(*CustomToolDefinition)(nil),   // 2: mcpagent.v1.CustomToolDefinition
	(*CreateAgentResponse)(nil),    // 3: mcpagent.v1.CreateAgentResponse
	(*Capabilities)(nil),           // 4: mcpagent.v1.Capabilities
	(*GetAgentRequest)(nil),        // 5: mcpagent.v1.GetAgentRequest
	(*GetAgentResponse)(nil),       // 6: mcpagent.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),      // 7: mcpagent.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),     // 8: mcpagent.v1.ListAgentsResponse
	(*AgentSummary)(nil),           // 9: mcpagent.v1.AgentSummary
	(*DestroyAgentRequest)(nil),    // 10: mcpagent.v1.DestroyAgentRequest
	(*DestroyAgentResponse)(nil),   // 11: mcpagent.v1.DestroyAgentResponse
	(*GetTokenUsageRequest)(nil),   // 12: mcpagent.v1.GetTokenUsageRequest
	(*TokenUsage)(nil),             // 13: mcpagent.v1.TokenUsage
	(*Costs)(nil),                  // 14: mcpagent.v1.Costs
	(*TokenUsageResponse)(nil),     // 15: mcpagent.v1.TokenUsageResponse
	(*ConversationRequest)(nil),    // 16: mcpagent.v1.ConversationRequest
	(*QuestionMessage)(nil),        // 17: mcpagent.v1.QuestionMessage
	(*ToolResultMessage)(nil),      // 18: mcpagent.v1.ToolResultMessage
	(*ToolError)(nil),              // 19: mcpagent.v1.ToolError
	(*CancelMessage)(nil),          // 20: mcpagent.v1.CancelMessage
	(*ConversationResponse)(nil),   // 21: mcpagent.v1.ConversationResponse
	(*TextChunkEvent)(nil),         // 22: mcpagent.v1.TextChunkEvent
	(*ToolCallEvent)(nil),          // 23: mcpagent.v1.ToolCallEvent
	(*FinalResponse)(nil),          // 24: mcpagent.v1.FinalResponse
	(*ErrorEvent)(nil),             // 25: mcpagent.v1.ErrorEvent
	(*AgentEvent)(nil),             // 26: mcpagent.v1.AgentEvent
	(*Message)(nil),                // 27: mcpagent.v1.Message
	(*AskRequest)(nil),             // 28: mcpagent.v1.AskRequest
	(*AskResponse)(nil),            // 29: mcpagent.v1.AskResponse
	(*AskWithHistoryRequest)(nil),  // 30: mcpagent.v1.AskWithHistoryRequest
	(*AskWithHistoryResponse)(nil), // 31: mcpagent.v1.AskWithHistoryResponse
	(*HealthCheckRequest)(nil),     // 32: mcpagent.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 33: mcpagent.v1.HealthCheckResponse
	(*structpb.Struct)(nil),        // 34: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 35: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: mcpagent.v1.CreateAgentRequest.config:type_name -> mcpagent.v1.AgentConfig
	2,  // 1: mcpagent.v1.AgentConfig.custom_tools:type_name -> mcpagent.v1.CustomToolDefinition
	34, // 2: mcpagent.v1.CustomToolDefinition.parameters:type_name -> google.protobuf.Struct
	35, // 3: mcpagent.v1.CreateAgentResponse.created_at:type_name -> google.protobuf.Timestamp
	4,  // 4: mcpagent.v1.CreateAgentResponse.capabilities:type_name -> mcpagent.v1.Capabilities
	35, // 5: mcpagent.v1.GetAgentResponse.created_at:type_name -> google.protobuf.Timestamp
	4,  // 6: mcpagent.v1.GetAgentResponse.capabilities:type_name -> mcpagent.v1.Capabilities
	13, // 7: mcpagent.v1.GetAgentResponse.token_usage:type_name -> mcpagent.v1.TokenUsage
	9,  // 8: mcpagent.v1.ListAgentsResponse.agents:type_name -> mcpagent.v1.AgentSummary
	35, // 9: mcpagent.v1.AgentSummary.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: mcpagent.v1.TokenUsageResponse.token_usage:type_name -> mcpagent.v1.TokenUsage
	14, // 11: mcpagent.v1.TokenUsageResponse.costs:type_name -> mcpagent.v1.Costs
	17, // 12: mcpagent.v1.ConversationRequest.question:type_name -> mcpagent.v1.QuestionMessage
	18, // 13: mcpagent.v1.ConversationRequest.tool_result:type_name -> mcpagent.v1.ToolResultMessage
	20, // 14: mcpagent.v1.ConversationRequest.cancel:type_name -> mcpagent.v1.CancelMessage
	27, // 15: mcpagent.v1.QuestionMessage.history:type_name -> mcpagent.v1.Message
	19, // 16: mcpagent.v1.ToolResultMessage.error:type_name -> mcpagent.v1.ToolError
	34, // 17: mcpagent.v1.ToolError.details:type_name -> google.protobuf.Struct
	22, // 18: mcpagent.v1.ConversationResponse.text_chunk:type_name -> mcpagent.v1.TextChunkEvent
	23, // 19: mcpagent.v1.ConversationResponse.tool_call:type_name -> mcpagent.v1.ToolCallEvent
	26, // 20: mcpagent.v1.ConversationResponse.agent_event:type_name -> mcpagent.v1.AgentEvent
	24, // 21: mcpagent.v1.ConversationResponse.final_response:type_name -> mcpagent.v1.FinalResponse
	25, // 22: mcpagent.v1.ConversationResponse.error:type_name -> mcpagent.v1.ErrorEvent
	34, // 23: mcpagent.v1.ToolCallEvent.arguments:type_name -> google.protobuf.Struct
	27, // 24: mcpagent.v1.FinalResponse.updated_messages:type_name -> mcpagent.v1.Message
	13, // 25: mcpagent.v1.FinalResponse.token_usage:type_name -> mcpagent.v1.TokenUsage
	34, // 26: mcpagent.v1.ErrorEvent.details:type_name -> google.protobuf.Struct
	35, // 27: mcpagent.v1.AgentEvent.timestamp:type_name -> google.protobuf.Timestamp
	34, // 28: mcpagent.v1.AgentEvent.data:type_name -> google.protobuf.Struct
	13, // 29: mcpagent.v1.AskResponse.token_usage:type_name -> mcpagent.v1.TokenUsage
	27, // 30: mcpagent.v1.AskWithHistoryRequest.messages:type_name -> mcpagent.v1.Message
	27, // 31: mcpagent.v1.AskWithHistoryResponse.updated_messages:type_name -> mcpagent.v1.Message
	13, // 32: mcpagent.v1.AskWithHistoryResponse.token_usage:type_name -> mcpagent.v1.TokenUsage
	0,  // 33: mcpagent.v1.AgentService.CreateAgent:input_type -> mcpagent.v1.CreateAgentRequest
	5,  // 34: mcpagent.v1.AgentService.GetAgent:input_type -> mcpagent.v1.GetAgentRequest
	7,  // 35: mcpagent.v1.AgentService.ListAgents:input_type -> mcpagent.v1.ListAgentsRequest
	10, // 36: mcpagent.v1.AgentService.DestroyAgent:input_type -> mcpagent.v1.DestroyAgentRequest
	12, // 37: mcpagent.v1.AgentService.GetTokenUsage:input_type -> mcpagent.v1.GetTokenUsageRequest
	16, // 38: mcpagent.v1.AgentService.Converse:input_type -> mcpagent.v1.ConversationRequest
	28, // 39: mcpagent.v1.AgentService.Ask:input_type -> mcpagent.v1.AskRequest
	30, // 40: mcpagent.v1.AgentService.AskWithHistory:input_type -> mcpagent.v1.AskWithHistoryRequest
	32, // 41: mcpagent.v1.AgentService.HealthCheck:input_type -> mcpagent.v1.HealthCheckRequest
	3,  // 42: mcpagent.v1.AgentService.CreateAgent:output_type -> mcpagent.v1.CreateAgentResponse
	6,  // 43: mcpagent.v1.AgentService.GetAgent:output_type -> mcpagent.v1.GetAgentResponse
	8,  // 44: mcpagent.v1.AgentService.ListAgents:output_type -> mcpagent.v1.ListAgentsResponse
	11, // 45: mcpagent.v1.AgentService.DestroyAgent:output_type -> mcpagent.v1.DestroyAgentResponse
	15, // 46: mcpagent.v1.AgentService.GetTokenUsage:output_type -> mcpagent.v1.TokenUsageResponse
	21, // 47: mcpagent.v1.AgentService.Converse:output_type -> mcpagent.v1.ConversationResponse
	29, // 48: mcpagent.v1.AgentService.Ask:output_type -> mcpagent.v1.AskResponse
	31, // 49: mcpagent.v1.AgentService.AskWithHistory:output_type -> mcpagent.v1.AskWithHistoryResponse
	33, // 50: mcpagent.v1.AgentService.HealthCheck:output_type -> mcpagent.v1.HealthCheckResponse
	42, // [42:51] is the sub-list for method output_type
	33, // [33:42] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[16].OneofWrappers = []any{
		(*ConversationRequest_Question)(nil),
		(*ConversationRequest_ToolResult)(nil),
		(*ConversationRequest_Cancel)(nil),
	}
	file_agent_proto_msgTypes[21].OneofWrappers = []any{
		(*ConversationResponse_TextChunk)(nil),
		(*ConversationResponse_ToolCall)(nil),
		(*ConversationResponse_AgentEvent)(nil),
		(*ConversationResponse_FinalResponse)(nil),
		(*ConversationResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
