package mcpagent

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/manishiitg/mcpagent/llm"
	loggerv2 "github.com/manishiitg/mcpagent/logger/v2"
	"github.com/manishiitg/multi-llm-provider-go/llmtypes"
)

// Captures the exact outbound system-message text, not just caller instructions.
// No model call or backend execution occurs. Fixtures can be generated by
// AgentWorks TestExportProductPromptFixtures with the same output directory.
func TestExportSystemPromptFixtures(t *testing.T) {
	outDir := os.Getenv("PROMPT_SNAPSHOT_DIR")
	if outDir == "" {
		t.Skip("set PROMPT_SNAPSHOT_DIR with AgentWorks fixtures.json")
	}
	if !filepath.IsAbs(outDir) {
		t.Fatal("PROMPT_SNAPSHOT_DIR must be absolute")
	}
	root, err := os.OpenRoot(outDir)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	raw, err := root.ReadFile("fixtures.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixtures []struct {
		Name         string
		Instructions string
		Skills       []*llmtypes.Skill
		ToolNames    []string
		Provider     string
	}
	if err := json.Unmarshal(raw, &fixtures); err != nil {
		t.Fatal(err)
	}
	config := filepath.Join(t.TempDir(), "mcp.json")
	if err := os.WriteFile(config, []byte(`{"mcpServers":{}}`), 0600); err != nil {
		t.Fatal(err)
	}
	type report struct {
		Name             string
		Provider         string
		SystemBytes      int
		SystemCharacters int
		Skills           []string
	}
	reports := []report{}
	for _, fixture := range fixtures {
		t.Run(fixture.Name, func(t *testing.T) {
			if filepath.Base(fixture.Name) != fixture.Name || fixture.Name == "." || fixture.Name == ".." {
				t.Fatal("invalid fixture name")
			}
			provider := llm.Provider(fixture.Provider)
			if override := os.Getenv("PROMPT_SNAPSHOT_PROVIDER"); override != "" {
				provider = llm.Provider(override)
			}
			switch provider {
			case llm.ProviderClaudeCode, llm.ProviderCodexCLI, llm.ProviderCursorCLI, llm.ProviderPiCLI, llm.ProviderMuseCLI, llm.ProviderAgyCLI:
			default:
				t.Fatalf("unsupported fixture CLI %s", provider)
			}
			definition := AgentDefinition{Instructions: fixture.Instructions, Skills: fixture.Skills}
			names := map[string]bool{}
			for _, name := range fixture.ToolNames {
				if names[name] {
					continue
				}
				names[name] = true
				definition.Tools.Direct = append(definition.Tools.Direct, ToolDefinition{Name: name, Description: "Fixture registration for " + name, InputSchema: map[string]interface{}{"type": "object"}, Execute: definitionNoopTool})
			}
			a, err := NewAgentFromDefinition(context.Background(), definition, RuntimeConfig{Model: linkedOutputFakeModel{}, MCPConfigPath: config, Generation: GenerationRuntimeConfig{Provider: provider}, Tools: ToolRuntimeConfig{CodeExecution: true, Discovery: true}, Coding: CodingRuntimeConfig{BridgeToolAdmit: func(name string) bool { return names[name] }}, Observability: ObservabilityRuntimeConfig{Logger: loggerv2.NewNoop()}})
			if err != nil {
				t.Fatal(err)
			}
			defer a.Close()
			prompt := a.outgoingSystemPrompt()
			if !strings.Contains(prompt, fixture.Instructions) || !strings.Contains(prompt, runtimeHTTPSkillName) || strings.Contains(prompt, "curl --fail-with-body") {
				t.Fatal("snapshot omitted product/runtime policy or inlined the moved tutorial")
			}
			view := a.Definition()
			for _, skill := range view.SkillDefinitions {
				if strings.Contains(prompt, skill.Content) && len(skill.Content) > 500 {
					t.Fatalf("skill body inlined: %s", skill.Name)
				}
			}
			path := filepath.Join(outDir, fixture.Name+".system.md")
			if err := root.WriteFile(fixture.Name+".system.md", []byte(prompt), 0600); err != nil {
				t.Fatal(err)
			}
			skillsJSON, err := json.MarshalIndent(view.SkillDefinitions, "", "  ")
			if err != nil {
				t.Fatal(err)
			}
			if err := root.WriteFile(fixture.Name+".skills.json", skillsJSON, 0600); err != nil {
				t.Fatal(err)
			}
			reports = append(reports, report{Name: fixture.Name, Provider: string(provider), SystemBytes: len(prompt), SystemCharacters: len([]rune(prompt)), Skills: view.Skills})
			t.Logf("OUTBOUND_PROMPT %s provider=%s bytes=%d skills=%d path=%s", fixture.Name, provider, len(prompt), len(view.Skills), path)
		})
	}
	summary, err := json.MarshalIndent(reports, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := root.WriteFile("summary.json", summary, 0600); err != nil {
		t.Fatal(err)
	}
	explanation := fmt.Sprintf("# Local prompt snapshots\n\nGenerated by the AgentWorks server composer and mcpagent outbound composer. No model call was made.\n\n*.system.md is the complete outgoing system text for each fixture. *.skills.json holds attached metadata and on-demand bodies; these bodies are not all in the system text. summary.json gives exact byte/character counts.\n\nInputs use example roots, a saved example Crew identity, builtin resolvable skills and fixture tool registrations. Real sessions may add user-selected skills, connections, secrets names, browser configuration, channel context or other grants. These are representative fixtures, not snapshots of a specific live user or total provider requests. CLI native skill indexes and tool schemas may also consume context outside system text.\n\nSource fixture count: %d.\n", len(fixtures))
	if err := root.WriteFile("README.md", []byte(explanation), 0600); err != nil {
		t.Fatal(err)
	}
}
